"""Batch runner — drives N parallel Matterix envs, collects safety statistics.

Matterix supports `num_envs=N` out of the box: all N environments share the
same GPU kernel, so 1000 parallel runs cost roughly the same wall-clock time
as a single run. `MatterixBatchRunner` exploits this to collect a statistical
risk profile in one pass.

Data model
----------
BatchRunResult   raw per-env and per-step counts from the run loop
StepStats        aggregate counts for one physics step (all N envs)
RiskProfile      derived safety summary with SafetySignal list

The raw `semantic_events` tensor is NOT stored per-env per-step (that would
be `N × max_steps × tensor_size` — too large). Only aggregate scalars are
kept per step. Full tensor access requires calibration against the real
Matterix semantic obs schema (see findings.md).

Usage (Linux + Isaac Lab installed):

    env = make_real_env(
        task="Matterix-Test-Beaker-Lift-Franka-v1",
        num_envs=1000,
        headless=True,
    )
    runner = MatterixBatchRunner(env)
    workflow = operation_to_workflow(PickAndPlace(...))
    result = runner.run_batch(workflow)
    profile = RiskProfile.from_batch(result)
    for sig in profile.signals:
        print(sig.level, sig.message)
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any

from twin_core.operations import WorkflowDict
from twin_core.safety import SafetySignal
from twin_core.schemas import Observation

from twin_sim.backend import SimRuntimeUnavailable
from twin_sim.real_runner import _obs_to_twin, _workflow_to_cfg_list


# ---------------------------------------------------------------------------
# Per-step aggregate
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class StepStats:
    """Aggregate counts for one physics step across all parallel envs.

    n_active    envs still running (not yet succeeded or SM-failed)
    n_succeeded cumulative envs whose SM reported action_sequence_success
    n_failed    cumulative envs whose SM reported action_sequence_failure
    """

    step_index: int
    n_active: int
    n_succeeded: int
    n_failed: int


# ---------------------------------------------------------------------------
# Raw batch result
# ---------------------------------------------------------------------------


@dataclass
class BatchRunResult:
    """Raw output of a single MatterixBatchRunner.run_batch() call.

    Memory note: final_observations stores one twin Observation per env
    (N items). step_stats stores aggregate counts per physics step
    (max_steps items). No per-env per-step tensors are stored.
    """

    n_envs: int
    success_count: int
    failure_count: int
    # Envs that hit max_steps without SM success or failure.
    timed_out_count: int
    success_rate: float   # success_count / n_envs
    failure_rate: float   # failure_count / n_envs
    total_physics_steps: int
    # Per-step aggregate (length = total_physics_steps).
    step_stats: list[StepStats]
    # Step at which env[i] first hit SM success; -1 if it did not succeed.
    env_success_steps: list[int]
    # Step at which env[i] first hit SM failure; -1 if it did not fail.
    env_failure_steps: list[int]
    # Twin observation at the final step for each env; None on key mismatch.
    final_observations: list[Observation | None]


# ---------------------------------------------------------------------------
# Risk profile — derived from BatchRunResult
# ---------------------------------------------------------------------------


@dataclass
class RiskProfile:
    """Safety summary derived from a BatchRunResult.

    Generated by RiskProfile.from_batch(). Consumed by the orchestrator to
    set monitoring thresholds or gate the real experiment.

    risky_steps   physics steps where >5 % of envs newly failed in that step
    signals       SafetySignal list ordered by severity then step_index
    """

    n_envs: int
    total_physics_steps: int
    success_rate: float
    failure_rate: float
    timeout_rate: float
    # None when no envs succeeded / failed.
    mean_steps_to_success: float | None
    mean_steps_to_failure: float | None
    step_stats: list[StepStats]
    risky_steps: list[int]
    signals: list[SafetySignal]

    @classmethod
    def from_batch(
        cls,
        batch: BatchRunResult,
        *,
        warning_threshold: float = 0.20,
        critical_threshold: float = 0.50,
        risky_step_delta: float = 0.05,
    ) -> RiskProfile:
        """Derive a RiskProfile from a BatchRunResult.

        warning_threshold   overall failure_rate above this → warning signal
        critical_threshold  overall failure_rate above this → critical signal
        risky_step_delta    fraction of envs newly failing in one step that
                            marks the step as risky (default 5 %)
        """
        n = batch.n_envs
        stats = batch.step_stats

        # Identify steps with a notable spike in new failures.
        risky_steps: list[int] = []
        prev_failed = 0
        for ss in stats:
            delta = ss.n_failed - prev_failed
            if n > 0 and delta / n >= risky_step_delta:
                risky_steps.append(ss.step_index)
            prev_failed = ss.n_failed

        # Build signals.
        signals: list[SafetySignal] = []

        # Overall failure rate signal.
        fr = batch.failure_rate
        if fr >= critical_threshold:
            signals.append(SafetySignal(
                level="critical",
                step_index=-1,
                source="failure_rate",
                message=(
                    f"Overall failure rate {fr:.1%} exceeds critical threshold "
                    f"{critical_threshold:.1%} across {n} envs"
                ),
                metadata={"failure_rate": fr, "n_envs": n,
                          "success_count": batch.success_count,
                          "failure_count": batch.failure_count},
            ))
        elif fr >= warning_threshold:
            signals.append(SafetySignal(
                level="warning",
                step_index=-1,
                source="failure_rate",
                message=(
                    f"Overall failure rate {fr:.1%} exceeds warning threshold "
                    f"{warning_threshold:.1%} across {n} envs"
                ),
                metadata={"failure_rate": fr, "n_envs": n,
                          "success_count": batch.success_count,
                          "failure_count": batch.failure_count},
            ))
        elif fr > 0:
            signals.append(SafetySignal(
                level="info",
                step_index=-1,
                source="failure_rate",
                message=f"Failure rate {fr:.1%} ({batch.failure_count}/{n} envs)",
                metadata={"failure_rate": fr, "n_envs": n},
            ))

        # Per-step risky step signals.
        prev_failed = 0
        for ss in stats:
            if ss.step_index not in risky_steps:
                prev_failed = ss.n_failed
                continue
            delta = ss.n_failed - prev_failed
            local_rate = delta / n if n > 0 else 0.0
            level: str = "critical" if local_rate >= critical_threshold else "warning"
            signals.append(SafetySignal(
                level=level,  # type: ignore[arg-type]
                step_index=ss.step_index,
                source="failure_rate",
                message=(
                    f"Step {ss.step_index}: {local_rate:.1%} of envs failed "
                    f"({delta}/{n} newly failed this step)"
                ),
                metadata={"local_failure_rate": local_rate,
                          "n_newly_failed": delta,
                          "cumulative_failed": ss.n_failed},
            ))
            prev_failed = ss.n_failed

        # Sort: critical first, then warning, then info; within level by step.
        _order = {"critical": 0, "warning": 1, "info": 2}
        signals.sort(key=lambda s: (_order[s.level], s.step_index))

        # Mean steps stats.
        success_steps_valid = [s for s in batch.env_success_steps if s != -1]
        failure_steps_valid = [s for s in batch.env_failure_steps if s != -1]

        return cls(
            n_envs=n,
            total_physics_steps=batch.total_physics_steps,
            success_rate=batch.success_rate,
            failure_rate=batch.failure_rate,
            timeout_rate=batch.timed_out_count / n if n > 0 else 0.0,
            mean_steps_to_success=(
                sum(success_steps_valid) / len(success_steps_valid)
                if success_steps_valid else None
            ),
            mean_steps_to_failure=(
                sum(failure_steps_valid) / len(failure_steps_valid)
                if failure_steps_valid else None
            ),
            step_stats=stats,
            risky_steps=risky_steps,
            signals=signals,
        )


# ---------------------------------------------------------------------------
# Batch runner
# ---------------------------------------------------------------------------


@dataclass
class MatterixBatchRunner:
    """Runs N parallel Matterix envs in one GPU pass, collecting risk stats.

    Construct the env with num_envs=N via make_real_env(..., num_envs=N).
    The SM runs all N envs simultaneously — wall-clock cost ≈ single run.
    """

    env: Any           # gymnasium env with num_envs=N, from make_real_env()
    robot_asset: str = "robot"
    max_steps: int = 5000

    def run_batch(self, workflow: WorkflowDict) -> BatchRunResult:
        """Run all N envs through the workflow and return aggregate results."""
        try:
            import torch  # type: ignore[import-not-found]
            from matterix_sm import StateMachine  # type: ignore[import-not-found]
        except ImportError as exc:  # pragma: no cover - runtime-only
            raise SimRuntimeUnavailable(
                "matterix_sm + torch required for MatterixBatchRunner"
            ) from exc

        n_envs: int = self.env.num_envs
        device = self.env.device
        cfgs = _workflow_to_cfg_list(workflow, self.robot_asset)

        sm = StateMachine(num_envs=n_envs, dt=self.env.step_dt, device=device)
        sm.set_action_sequence(cfgs)

        obs, _ = self.env.reset()
        sm.reset()

        # Per-env completion tracking (step index; -1 = not yet).
        env_success_steps = torch.full((n_envs,), -1, dtype=torch.long, device=device)
        env_failure_steps = torch.full((n_envs,), -1, dtype=torch.long, device=device)

        step_stats: list[StepStats] = []
        step_count = 0

        with torch.inference_mode():
            while step_count < self.max_steps:
                done = sm.action_sequence_success | sm.action_sequence_failure
                if bool(done.all()):
                    break

                action, semantic_actions = sm.step(obs)
                action = action.to(device)
                obs, _, terminated, truncated, _ = self.env.step(
                    action, semantic_actions=semantic_actions
                )
                step_count += 1

                # Record the step at which each env first reaches success/failure.
                newly_succeeded = sm.action_sequence_success & (env_success_steps == -1)
                newly_failed = sm.action_sequence_failure & (env_failure_steps == -1)
                env_success_steps[newly_succeeded] = step_count
                env_failure_steps[newly_failed] = step_count

                n_succeeded = int(sm.action_sequence_success.sum().item())
                n_failed = int(sm.action_sequence_failure.sum().item())
                step_stats.append(StepStats(
                    step_index=step_count,
                    n_active=n_envs - n_succeeded - n_failed,
                    n_succeeded=n_succeeded,
                    n_failed=n_failed,
                ))

                # Reset envs that Isaac Lab terminated/truncated early so they
                # don't stall the SM loop. Their failure is already recorded.
                reset_ids = (terminated | truncated).nonzero(as_tuple=False).flatten()
                if reset_ids.numel() > 0:
                    sm.reset_envs(reset_ids)

        final_success = int(sm.action_sequence_success.sum().item())
        final_failure = int(sm.action_sequence_failure.sum().item())
        timed_out = n_envs - final_success - final_failure

        success_steps_list = env_success_steps.tolist()
        failure_steps_list = env_failure_steps.tolist()

        # Extract per-env final observations (one twin Observation per env).
        final_observations = [
            _obs_to_twin(obs, self.robot_asset, env_idx=i)
            for i in range(n_envs)
        ]

        return BatchRunResult(
            n_envs=n_envs,
            success_count=final_success,
            failure_count=final_failure,
            timed_out_count=timed_out,
            success_rate=final_success / n_envs if n_envs > 0 else 0.0,
            failure_rate=final_failure / n_envs if n_envs > 0 else 0.0,
            total_physics_steps=step_count,
            step_stats=step_stats,
            env_success_steps=success_steps_list,
            env_failure_steps=failure_steps_list,
            final_observations=final_observations,
        )
